language: python
sudo: false
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -f -b -p $PWD/miniconda3
  - export PATH=$PWD/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # install setup environment
  - bash install.sh
before_script:
  - echo 'foo'
  # - source activate shotgun-humann2; humann2 --version; source deactivate;
  # - source activate shotgun-qc; atropos --version; source deactivate;
  # - source activate shotgun-shogun; shogun_utree_lca; source deactivate;
script:
  # run workflow
  - export PATH=$PATH:$PWD/utree
  - source activate oecophylla
  - snakemake all --cores 2
after_success:
  - coveralls